project_name: npt
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/npt
    binary: npt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/hsn723/npt/cmd.version={{.Version}}
      - -X github.com/hsn723/npt/cmd.commit={{.Commit}}
      - -X github.com/hsn723/npt/cmd.date={{.Date}}
      - -X github.com/hsn723/npt/cmd.builtBy=goreleaser
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  use: github-native
source:
  enabled: true
sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source
signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - --yes
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: all
    output: true
